### ISSUE TITLE
Apparatus No Change Value

### ISSUE THREAD

**Issue by DHStyle541** [Goryaa/WeatherMultipliers#1]
Hi, about WeatherMultipliers v1.0.0 / Latest
the Apparatus still 80 no changed value
This is Flooded (65%)
![image](https://github.com/Goryaa/WeatherMultipliers/assets/154591650/60ca777a-3976-4344-94a2-26f7ab733141)

This is Eclipse (100%)
![image](https://github.com/Goryaa/WeatherMultipliers/assets/154591650/6db24576-a1d0-4fd8-9454-a3dc8f13f7a6)

**Comment by Goryaa** [comment]
Was this before you grabbed it from the facility. If so, I think I know what the issue is. If that is the case, then it should properly have its value updated once it is picked up.

**Comment by DHStyle541** [comment]
still same, when i picked up and drop on ship.
